'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace acceso
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="acceso.accesoServSoap")>  _
    Public Interface accesoServSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento hiResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/hi", ReplyAction:="*")>  _
        Function hi(ByVal request As acceso.hiRequest) As acceso.hiResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/hi", ReplyAction:="*")>  _
        Function hiAsync(ByVal request As acceso.hiRequest) As System.Threading.Tasks.Task(Of acceso.hiResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/checar_accesoUsuario", ReplyAction:="*")>  _
        Function checar_accesoUsuario(ByVal request As acceso.checar_accesoUsuarioRequest) As acceso.checar_accesoUsuarioResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/checar_accesoUsuario", ReplyAction:="*")>  _
        Function checar_accesoUsuarioAsync(ByVal request As acceso.checar_accesoUsuarioRequest) As System.Threading.Tasks.Task(Of acceso.checar_accesoUsuarioResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento id_usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/checar_acceso", ReplyAction:="*")>  _
        Function checar_acceso(ByVal request As acceso.checar_accesoRequest) As acceso.checar_accesoResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/checar_acceso", ReplyAction:="*")>  _
        Function checar_accesoAsync(ByVal request As acceso.checar_accesoRequest) As System.Threading.Tasks.Task(Of acceso.checar_accesoResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento obtener_sub_menusResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/obtener_sub_menus", ReplyAction:="*")>  _
        Function obtener_sub_menus(ByVal request As acceso.obtener_sub_menusRequest) As acceso.obtener_sub_menusResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/obtener_sub_menus", ReplyAction:="*")>  _
        Function obtener_sub_menusAsync(ByVal request As acceso.obtener_sub_menusRequest) As System.Threading.Tasks.Task(Of acceso.obtener_sub_menusResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Obtener_lista_usuariosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Obtener_lista_usuarios", ReplyAction:="*")>  _
        Function Obtener_lista_usuarios(ByVal request As acceso.Obtener_lista_usuariosRequest) As acceso.Obtener_lista_usuariosResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Obtener_lista_usuarios", ReplyAction:="*")>  _
        Function Obtener_lista_usuariosAsync(ByVal request As acceso.Obtener_lista_usuariosRequest) As System.Threading.Tasks.Task(Of acceso.Obtener_lista_usuariosResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento UsuariosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Usuarios", ReplyAction:="*")>  _
        Function Usuarios(ByVal request As acceso.UsuariosRequest) As acceso.UsuariosResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Usuarios", ReplyAction:="*")>  _
        Function UsuariosAsync(ByVal request As acceso.UsuariosRequest) As System.Threading.Tasks.Task(Of acceso.UsuariosResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/guardar", ReplyAction:="*")>  _
        Function guardar(ByVal request As acceso.guardarRequest) As acceso.guardarResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/guardar", ReplyAction:="*")>  _
        Function guardarAsync(ByVal request As acceso.guardarRequest) As System.Threading.Tasks.Task(Of acceso.guardarResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/borrar", ReplyAction:="*")>  _
        Function borrar(ByVal request As acceso.borrarRequest) As acceso.borrarResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/borrar", ReplyAction:="*")>  _
        Function borrarAsync(ByVal request As acceso.borrarRequest) As System.Threading.Tasks.Task(Of acceso.borrarResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento id_usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/checar_acceso_subMenu", ReplyAction:="*")>  _
        Function checar_acceso_subMenu(ByVal request As acceso.checar_acceso_subMenuRequest) As acceso.checar_acceso_subMenuResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/checar_acceso_subMenu", ReplyAction:="*")>  _
        Function checar_acceso_subMenuAsync(ByVal request As acceso.checar_acceso_subMenuRequest) As System.Threading.Tasks.Task(Of acceso.checar_acceso_subMenuResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre_corto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/actualizar_usuario", ReplyAction:="*")>  _
        Function actualizar_usuario(ByVal request As acceso.actualizar_usuarioRequest) As acceso.actualizar_usuarioResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/actualizar_usuario", ReplyAction:="*")>  _
        Function actualizar_usuarioAsync(ByVal request As acceso.actualizar_usuarioRequest) As System.Threading.Tasks.Task(Of acceso.actualizar_usuarioResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre_corto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/guardar_usuario", ReplyAction:="*")>  _
        Function guardar_usuario(ByVal request As acceso.guardar_usuarioRequest) As acceso.guardar_usuarioResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/guardar_usuario", ReplyAction:="*")>  _
        Function guardar_usuarioAsync(ByVal request As acceso.guardar_usuarioRequest) As System.Threading.Tasks.Task(Of acceso.guardar_usuarioResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento id_usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/eliminar_usuario", ReplyAction:="*")>  _
        Function eliminar_usuario(ByVal request As acceso.eliminar_usuarioRequest) As acceso.eliminar_usuarioResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/eliminar_usuario", ReplyAction:="*")>  _
        Function eliminar_usuarioAsync(ByVal request As acceso.eliminar_usuarioRequest) As System.Threading.Tasks.Task(Of acceso.eliminar_usuarioResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento id del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/cambio_contrasenia", ReplyAction:="*")>  _
        Function cambio_contrasenia(ByVal request As acceso.cambio_contraseniaRequest) As acceso.cambio_contraseniaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/cambio_contrasenia", ReplyAction:="*")>  _
        Function cambio_contraseniaAsync(ByVal request As acceso.cambio_contraseniaRequest) As System.Threading.Tasks.Task(Of acceso.cambio_contraseniaResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class hiRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="hi", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As acceso.hiRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As acceso.hiRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class hiRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class hiResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="hiResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As acceso.hiResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As acceso.hiResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class hiResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public hiResult As Object
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal hiResult As Object)
            MyBase.New
            Me.hiResult = hiResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class checar_accesoUsuarioRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="checar_accesoUsuario", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As acceso.checar_accesoUsuarioRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As acceso.checar_accesoUsuarioRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class checar_accesoUsuarioRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public nombre As Object
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As Object
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nombre As Object, ByVal password As Object)
            MyBase.New
            Me.nombre = nombre
            Me.password = password
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class checar_accesoUsuarioResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="checar_accesoUsuarioResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As acceso.checar_accesoUsuarioResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As acceso.checar_accesoUsuarioResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class checar_accesoUsuarioResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public checar_accesoUsuarioResult As Object
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal checar_accesoUsuarioResult As Object)
            MyBase.New
            Me.checar_accesoUsuarioResult = checar_accesoUsuarioResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class checar_accesoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="checar_acceso", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As acceso.checar_accesoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As acceso.checar_accesoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class checar_accesoRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public id_usuario As Object
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal id_usuario As Object)
            MyBase.New
            Me.id_usuario = id_usuario
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class checar_accesoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="checar_accesoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As acceso.checar_accesoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As acceso.checar_accesoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class checar_accesoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public checar_accesoResult As Object
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal checar_accesoResult As Object)
            MyBase.New
            Me.checar_accesoResult = checar_accesoResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class obtener_sub_menusRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="obtener_sub_menus", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As acceso.obtener_sub_menusRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As acceso.obtener_sub_menusRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class obtener_sub_menusRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class obtener_sub_menusResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="obtener_sub_menusResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As acceso.obtener_sub_menusResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As acceso.obtener_sub_menusResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class obtener_sub_menusResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public obtener_sub_menusResult As Object
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal obtener_sub_menusResult As Object)
            MyBase.New
            Me.obtener_sub_menusResult = obtener_sub_menusResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Obtener_lista_usuariosRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Obtener_lista_usuarios", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As acceso.Obtener_lista_usuariosRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As acceso.Obtener_lista_usuariosRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class Obtener_lista_usuariosRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Obtener_lista_usuariosResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Obtener_lista_usuariosResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As acceso.Obtener_lista_usuariosResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As acceso.Obtener_lista_usuariosResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Obtener_lista_usuariosResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Obtener_lista_usuariosResult As Object
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Obtener_lista_usuariosResult As Object)
            MyBase.New
            Me.Obtener_lista_usuariosResult = Obtener_lista_usuariosResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UsuariosRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Usuarios", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As acceso.UsuariosRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As acceso.UsuariosRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class UsuariosRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UsuariosResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UsuariosResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As acceso.UsuariosResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As acceso.UsuariosResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class UsuariosResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public UsuariosResult As Object
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UsuariosResult As Object)
            MyBase.New
            Me.UsuariosResult = UsuariosResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class guardarRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="guardar", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As acceso.guardarRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As acceso.guardarRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class guardarRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public usuario As Object
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public folio_sub_menu As Object
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public acceso As Object
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuario As Object, ByVal folio_sub_menu As Object, ByVal acceso As Object)
            MyBase.New
            Me.usuario = usuario
            Me.folio_sub_menu = folio_sub_menu
            Me.acceso = acceso
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class guardarResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="guardarResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As acceso.guardarResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As acceso.guardarResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class guardarResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class borrarRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="borrar", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As acceso.borrarRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As acceso.borrarRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class borrarRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public usuario As Object
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuario As Object)
            MyBase.New
            Me.usuario = usuario
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class borrarResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="borrarResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As acceso.borrarResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As acceso.borrarResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class borrarResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class checar_acceso_subMenuRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="checar_acceso_subMenu", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As acceso.checar_acceso_subMenuRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As acceso.checar_acceso_subMenuRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class checar_acceso_subMenuRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public id_usuario As Object
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public folio_sub_menu As Object
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal id_usuario As Object, ByVal folio_sub_menu As Object)
            MyBase.New
            Me.id_usuario = id_usuario
            Me.folio_sub_menu = folio_sub_menu
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class checar_acceso_subMenuResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="checar_acceso_subMenuResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As acceso.checar_acceso_subMenuResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As acceso.checar_acceso_subMenuResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class checar_acceso_subMenuResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public checar_acceso_subMenuResult As Object
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal checar_acceso_subMenuResult As Object)
            MyBase.New
            Me.checar_acceso_subMenuResult = checar_acceso_subMenuResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class actualizar_usuarioRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="actualizar_usuario", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As acceso.actualizar_usuarioRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As acceso.actualizar_usuarioRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class actualizar_usuarioRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public nombre_corto As Object
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Nombre_completo As Object
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public email_usuario As Object
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public nivel_usuario As Object
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public pasword As Object
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public id_scoi As Object
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public id_usuario As Object
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nombre_corto As Object, ByVal Nombre_completo As Object, ByVal email_usuario As Object, ByVal nivel_usuario As Object, ByVal pasword As Object, ByVal id_scoi As Object, ByVal id_usuario As Object)
            MyBase.New
            Me.nombre_corto = nombre_corto
            Me.Nombre_completo = Nombre_completo
            Me.email_usuario = email_usuario
            Me.nivel_usuario = nivel_usuario
            Me.pasword = pasword
            Me.id_scoi = id_scoi
            Me.id_usuario = id_usuario
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class actualizar_usuarioResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="actualizar_usuarioResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As acceso.actualizar_usuarioResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As acceso.actualizar_usuarioResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class actualizar_usuarioResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public actualizar_usuarioResult As Object
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal actualizar_usuarioResult As Object)
            MyBase.New
            Me.actualizar_usuarioResult = actualizar_usuarioResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class guardar_usuarioRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="guardar_usuario", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As acceso.guardar_usuarioRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As acceso.guardar_usuarioRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class guardar_usuarioRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public nombre_corto As Object
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Nombre_completo As Object
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public email_usuario As Object
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public nivel_usuario As Object
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public pasword As Object
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public id_scoi As Object
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public id_usuario As Object
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nombre_corto As Object, ByVal Nombre_completo As Object, ByVal email_usuario As Object, ByVal nivel_usuario As Object, ByVal pasword As Object, ByVal id_scoi As Object, ByVal id_usuario As Object)
            MyBase.New
            Me.nombre_corto = nombre_corto
            Me.Nombre_completo = Nombre_completo
            Me.email_usuario = email_usuario
            Me.nivel_usuario = nivel_usuario
            Me.pasword = pasword
            Me.id_scoi = id_scoi
            Me.id_usuario = id_usuario
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class guardar_usuarioResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="guardar_usuarioResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As acceso.guardar_usuarioResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As acceso.guardar_usuarioResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class guardar_usuarioResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public guardar_usuarioResult As Object
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal guardar_usuarioResult As Object)
            MyBase.New
            Me.guardar_usuarioResult = guardar_usuarioResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class eliminar_usuarioRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="eliminar_usuario", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As acceso.eliminar_usuarioRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As acceso.eliminar_usuarioRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class eliminar_usuarioRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public id_usuario As Object
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal id_usuario As Object)
            MyBase.New
            Me.id_usuario = id_usuario
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class eliminar_usuarioResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="eliminar_usuarioResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As acceso.eliminar_usuarioResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As acceso.eliminar_usuarioResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class eliminar_usuarioResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public eliminar_usuarioResult As Object
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal eliminar_usuarioResult As Object)
            MyBase.New
            Me.eliminar_usuarioResult = eliminar_usuarioResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class cambio_contraseniaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="cambio_contrasenia", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As acceso.cambio_contraseniaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As acceso.cambio_contraseniaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class cambio_contraseniaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public id As Object
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public pasword As Object
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal id As Object, ByVal pasword As Object)
            MyBase.New
            Me.id = id
            Me.pasword = pasword
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class cambio_contraseniaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="cambio_contraseniaResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As acceso.cambio_contraseniaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As acceso.cambio_contraseniaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class cambio_contraseniaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public cambio_contraseniaResult As Object
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal cambio_contraseniaResult As Object)
            MyBase.New
            Me.cambio_contraseniaResult = cambio_contraseniaResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface accesoServSoapChannel
        Inherits acceso.accesoServSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class accesoServSoapClient
        Inherits System.ServiceModel.ClientBase(Of acceso.accesoServSoap)
        Implements acceso.accesoServSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function acceso_accesoServSoap_hi(ByVal request As acceso.hiRequest) As acceso.hiResponse Implements acceso.accesoServSoap.hi
            Return MyBase.Channel.hi(request)
        End Function
        
        Public Function hi() As Object
            Dim inValue As acceso.hiRequest = New acceso.hiRequest()
            inValue.Body = New acceso.hiRequestBody()
            Dim retVal As acceso.hiResponse = CType(Me,acceso.accesoServSoap).hi(inValue)
            Return retVal.Body.hiResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function acceso_accesoServSoap_hiAsync(ByVal request As acceso.hiRequest) As System.Threading.Tasks.Task(Of acceso.hiResponse) Implements acceso.accesoServSoap.hiAsync
            Return MyBase.Channel.hiAsync(request)
        End Function
        
        Public Function hiAsync() As System.Threading.Tasks.Task(Of acceso.hiResponse)
            Dim inValue As acceso.hiRequest = New acceso.hiRequest()
            inValue.Body = New acceso.hiRequestBody()
            Return CType(Me,acceso.accesoServSoap).hiAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function acceso_accesoServSoap_checar_accesoUsuario(ByVal request As acceso.checar_accesoUsuarioRequest) As acceso.checar_accesoUsuarioResponse Implements acceso.accesoServSoap.checar_accesoUsuario
            Return MyBase.Channel.checar_accesoUsuario(request)
        End Function
        
        Public Function checar_accesoUsuario(ByVal nombre As Object, ByVal password As Object) As Object
            Dim inValue As acceso.checar_accesoUsuarioRequest = New acceso.checar_accesoUsuarioRequest()
            inValue.Body = New acceso.checar_accesoUsuarioRequestBody()
            inValue.Body.nombre = nombre
            inValue.Body.password = password
            Dim retVal As acceso.checar_accesoUsuarioResponse = CType(Me,acceso.accesoServSoap).checar_accesoUsuario(inValue)
            Return retVal.Body.checar_accesoUsuarioResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function acceso_accesoServSoap_checar_accesoUsuarioAsync(ByVal request As acceso.checar_accesoUsuarioRequest) As System.Threading.Tasks.Task(Of acceso.checar_accesoUsuarioResponse) Implements acceso.accesoServSoap.checar_accesoUsuarioAsync
            Return MyBase.Channel.checar_accesoUsuarioAsync(request)
        End Function
        
        Public Function checar_accesoUsuarioAsync(ByVal nombre As Object, ByVal password As Object) As System.Threading.Tasks.Task(Of acceso.checar_accesoUsuarioResponse)
            Dim inValue As acceso.checar_accesoUsuarioRequest = New acceso.checar_accesoUsuarioRequest()
            inValue.Body = New acceso.checar_accesoUsuarioRequestBody()
            inValue.Body.nombre = nombre
            inValue.Body.password = password
            Return CType(Me,acceso.accesoServSoap).checar_accesoUsuarioAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function acceso_accesoServSoap_checar_acceso(ByVal request As acceso.checar_accesoRequest) As acceso.checar_accesoResponse Implements acceso.accesoServSoap.checar_acceso
            Return MyBase.Channel.checar_acceso(request)
        End Function
        
        Public Function checar_acceso(ByVal id_usuario As Object) As Object
            Dim inValue As acceso.checar_accesoRequest = New acceso.checar_accesoRequest()
            inValue.Body = New acceso.checar_accesoRequestBody()
            inValue.Body.id_usuario = id_usuario
            Dim retVal As acceso.checar_accesoResponse = CType(Me,acceso.accesoServSoap).checar_acceso(inValue)
            Return retVal.Body.checar_accesoResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function acceso_accesoServSoap_checar_accesoAsync(ByVal request As acceso.checar_accesoRequest) As System.Threading.Tasks.Task(Of acceso.checar_accesoResponse) Implements acceso.accesoServSoap.checar_accesoAsync
            Return MyBase.Channel.checar_accesoAsync(request)
        End Function
        
        Public Function checar_accesoAsync(ByVal id_usuario As Object) As System.Threading.Tasks.Task(Of acceso.checar_accesoResponse)
            Dim inValue As acceso.checar_accesoRequest = New acceso.checar_accesoRequest()
            inValue.Body = New acceso.checar_accesoRequestBody()
            inValue.Body.id_usuario = id_usuario
            Return CType(Me,acceso.accesoServSoap).checar_accesoAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function acceso_accesoServSoap_obtener_sub_menus(ByVal request As acceso.obtener_sub_menusRequest) As acceso.obtener_sub_menusResponse Implements acceso.accesoServSoap.obtener_sub_menus
            Return MyBase.Channel.obtener_sub_menus(request)
        End Function
        
        Public Function obtener_sub_menus() As Object
            Dim inValue As acceso.obtener_sub_menusRequest = New acceso.obtener_sub_menusRequest()
            inValue.Body = New acceso.obtener_sub_menusRequestBody()
            Dim retVal As acceso.obtener_sub_menusResponse = CType(Me,acceso.accesoServSoap).obtener_sub_menus(inValue)
            Return retVal.Body.obtener_sub_menusResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function acceso_accesoServSoap_obtener_sub_menusAsync(ByVal request As acceso.obtener_sub_menusRequest) As System.Threading.Tasks.Task(Of acceso.obtener_sub_menusResponse) Implements acceso.accesoServSoap.obtener_sub_menusAsync
            Return MyBase.Channel.obtener_sub_menusAsync(request)
        End Function
        
        Public Function obtener_sub_menusAsync() As System.Threading.Tasks.Task(Of acceso.obtener_sub_menusResponse)
            Dim inValue As acceso.obtener_sub_menusRequest = New acceso.obtener_sub_menusRequest()
            inValue.Body = New acceso.obtener_sub_menusRequestBody()
            Return CType(Me,acceso.accesoServSoap).obtener_sub_menusAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function acceso_accesoServSoap_Obtener_lista_usuarios(ByVal request As acceso.Obtener_lista_usuariosRequest) As acceso.Obtener_lista_usuariosResponse Implements acceso.accesoServSoap.Obtener_lista_usuarios
            Return MyBase.Channel.Obtener_lista_usuarios(request)
        End Function
        
        Public Function Obtener_lista_usuarios() As Object
            Dim inValue As acceso.Obtener_lista_usuariosRequest = New acceso.Obtener_lista_usuariosRequest()
            inValue.Body = New acceso.Obtener_lista_usuariosRequestBody()
            Dim retVal As acceso.Obtener_lista_usuariosResponse = CType(Me,acceso.accesoServSoap).Obtener_lista_usuarios(inValue)
            Return retVal.Body.Obtener_lista_usuariosResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function acceso_accesoServSoap_Obtener_lista_usuariosAsync(ByVal request As acceso.Obtener_lista_usuariosRequest) As System.Threading.Tasks.Task(Of acceso.Obtener_lista_usuariosResponse) Implements acceso.accesoServSoap.Obtener_lista_usuariosAsync
            Return MyBase.Channel.Obtener_lista_usuariosAsync(request)
        End Function
        
        Public Function Obtener_lista_usuariosAsync() As System.Threading.Tasks.Task(Of acceso.Obtener_lista_usuariosResponse)
            Dim inValue As acceso.Obtener_lista_usuariosRequest = New acceso.Obtener_lista_usuariosRequest()
            inValue.Body = New acceso.Obtener_lista_usuariosRequestBody()
            Return CType(Me,acceso.accesoServSoap).Obtener_lista_usuariosAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function acceso_accesoServSoap_Usuarios(ByVal request As acceso.UsuariosRequest) As acceso.UsuariosResponse Implements acceso.accesoServSoap.Usuarios
            Return MyBase.Channel.Usuarios(request)
        End Function
        
        Public Function Usuarios() As Object
            Dim inValue As acceso.UsuariosRequest = New acceso.UsuariosRequest()
            inValue.Body = New acceso.UsuariosRequestBody()
            Dim retVal As acceso.UsuariosResponse = CType(Me,acceso.accesoServSoap).Usuarios(inValue)
            Return retVal.Body.UsuariosResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function acceso_accesoServSoap_UsuariosAsync(ByVal request As acceso.UsuariosRequest) As System.Threading.Tasks.Task(Of acceso.UsuariosResponse) Implements acceso.accesoServSoap.UsuariosAsync
            Return MyBase.Channel.UsuariosAsync(request)
        End Function
        
        Public Function UsuariosAsync() As System.Threading.Tasks.Task(Of acceso.UsuariosResponse)
            Dim inValue As acceso.UsuariosRequest = New acceso.UsuariosRequest()
            inValue.Body = New acceso.UsuariosRequestBody()
            Return CType(Me,acceso.accesoServSoap).UsuariosAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function acceso_accesoServSoap_guardar(ByVal request As acceso.guardarRequest) As acceso.guardarResponse Implements acceso.accesoServSoap.guardar
            Return MyBase.Channel.guardar(request)
        End Function
        
        Public Sub guardar(ByVal usuario As Object, ByVal folio_sub_menu As Object, ByVal acceso As Object)
            Dim inValue As acceso.guardarRequest = New acceso.guardarRequest()
            inValue.Body = New acceso.guardarRequestBody()
            inValue.Body.usuario = usuario
            inValue.Body.folio_sub_menu = folio_sub_menu
            inValue.Body.acceso = acceso
            Dim retVal As acceso.guardarResponse = CType(Me,acceso.accesoServSoap).guardar(inValue)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function acceso_accesoServSoap_guardarAsync(ByVal request As acceso.guardarRequest) As System.Threading.Tasks.Task(Of acceso.guardarResponse) Implements acceso.accesoServSoap.guardarAsync
            Return MyBase.Channel.guardarAsync(request)
        End Function
        
        Public Function guardarAsync(ByVal usuario As Object, ByVal folio_sub_menu As Object, ByVal acceso As Object) As System.Threading.Tasks.Task(Of acceso.guardarResponse)
            Dim inValue As acceso.guardarRequest = New acceso.guardarRequest()
            inValue.Body = New acceso.guardarRequestBody()
            inValue.Body.usuario = usuario
            inValue.Body.folio_sub_menu = folio_sub_menu
            inValue.Body.acceso = acceso
            Return CType(Me,acceso.accesoServSoap).guardarAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function acceso_accesoServSoap_borrar(ByVal request As acceso.borrarRequest) As acceso.borrarResponse Implements acceso.accesoServSoap.borrar
            Return MyBase.Channel.borrar(request)
        End Function
        
        Public Sub borrar(ByVal usuario As Object)
            Dim inValue As acceso.borrarRequest = New acceso.borrarRequest()
            inValue.Body = New acceso.borrarRequestBody()
            inValue.Body.usuario = usuario
            Dim retVal As acceso.borrarResponse = CType(Me,acceso.accesoServSoap).borrar(inValue)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function acceso_accesoServSoap_borrarAsync(ByVal request As acceso.borrarRequest) As System.Threading.Tasks.Task(Of acceso.borrarResponse) Implements acceso.accesoServSoap.borrarAsync
            Return MyBase.Channel.borrarAsync(request)
        End Function
        
        Public Function borrarAsync(ByVal usuario As Object) As System.Threading.Tasks.Task(Of acceso.borrarResponse)
            Dim inValue As acceso.borrarRequest = New acceso.borrarRequest()
            inValue.Body = New acceso.borrarRequestBody()
            inValue.Body.usuario = usuario
            Return CType(Me,acceso.accesoServSoap).borrarAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function acceso_accesoServSoap_checar_acceso_subMenu(ByVal request As acceso.checar_acceso_subMenuRequest) As acceso.checar_acceso_subMenuResponse Implements acceso.accesoServSoap.checar_acceso_subMenu
            Return MyBase.Channel.checar_acceso_subMenu(request)
        End Function
        
        Public Function checar_acceso_subMenu(ByVal id_usuario As Object, ByVal folio_sub_menu As Object) As Object
            Dim inValue As acceso.checar_acceso_subMenuRequest = New acceso.checar_acceso_subMenuRequest()
            inValue.Body = New acceso.checar_acceso_subMenuRequestBody()
            inValue.Body.id_usuario = id_usuario
            inValue.Body.folio_sub_menu = folio_sub_menu
            Dim retVal As acceso.checar_acceso_subMenuResponse = CType(Me,acceso.accesoServSoap).checar_acceso_subMenu(inValue)
            Return retVal.Body.checar_acceso_subMenuResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function acceso_accesoServSoap_checar_acceso_subMenuAsync(ByVal request As acceso.checar_acceso_subMenuRequest) As System.Threading.Tasks.Task(Of acceso.checar_acceso_subMenuResponse) Implements acceso.accesoServSoap.checar_acceso_subMenuAsync
            Return MyBase.Channel.checar_acceso_subMenuAsync(request)
        End Function
        
        Public Function checar_acceso_subMenuAsync(ByVal id_usuario As Object, ByVal folio_sub_menu As Object) As System.Threading.Tasks.Task(Of acceso.checar_acceso_subMenuResponse)
            Dim inValue As acceso.checar_acceso_subMenuRequest = New acceso.checar_acceso_subMenuRequest()
            inValue.Body = New acceso.checar_acceso_subMenuRequestBody()
            inValue.Body.id_usuario = id_usuario
            inValue.Body.folio_sub_menu = folio_sub_menu
            Return CType(Me,acceso.accesoServSoap).checar_acceso_subMenuAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function acceso_accesoServSoap_actualizar_usuario(ByVal request As acceso.actualizar_usuarioRequest) As acceso.actualizar_usuarioResponse Implements acceso.accesoServSoap.actualizar_usuario
            Return MyBase.Channel.actualizar_usuario(request)
        End Function
        
        Public Function actualizar_usuario(ByVal nombre_corto As Object, ByVal Nombre_completo As Object, ByVal email_usuario As Object, ByVal nivel_usuario As Object, ByVal pasword As Object, ByVal id_scoi As Object, ByVal id_usuario As Object) As Object
            Dim inValue As acceso.actualizar_usuarioRequest = New acceso.actualizar_usuarioRequest()
            inValue.Body = New acceso.actualizar_usuarioRequestBody()
            inValue.Body.nombre_corto = nombre_corto
            inValue.Body.Nombre_completo = Nombre_completo
            inValue.Body.email_usuario = email_usuario
            inValue.Body.nivel_usuario = nivel_usuario
            inValue.Body.pasword = pasword
            inValue.Body.id_scoi = id_scoi
            inValue.Body.id_usuario = id_usuario
            Dim retVal As acceso.actualizar_usuarioResponse = CType(Me,acceso.accesoServSoap).actualizar_usuario(inValue)
            Return retVal.Body.actualizar_usuarioResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function acceso_accesoServSoap_actualizar_usuarioAsync(ByVal request As acceso.actualizar_usuarioRequest) As System.Threading.Tasks.Task(Of acceso.actualizar_usuarioResponse) Implements acceso.accesoServSoap.actualizar_usuarioAsync
            Return MyBase.Channel.actualizar_usuarioAsync(request)
        End Function
        
        Public Function actualizar_usuarioAsync(ByVal nombre_corto As Object, ByVal Nombre_completo As Object, ByVal email_usuario As Object, ByVal nivel_usuario As Object, ByVal pasword As Object, ByVal id_scoi As Object, ByVal id_usuario As Object) As System.Threading.Tasks.Task(Of acceso.actualizar_usuarioResponse)
            Dim inValue As acceso.actualizar_usuarioRequest = New acceso.actualizar_usuarioRequest()
            inValue.Body = New acceso.actualizar_usuarioRequestBody()
            inValue.Body.nombre_corto = nombre_corto
            inValue.Body.Nombre_completo = Nombre_completo
            inValue.Body.email_usuario = email_usuario
            inValue.Body.nivel_usuario = nivel_usuario
            inValue.Body.pasword = pasword
            inValue.Body.id_scoi = id_scoi
            inValue.Body.id_usuario = id_usuario
            Return CType(Me,acceso.accesoServSoap).actualizar_usuarioAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function acceso_accesoServSoap_guardar_usuario(ByVal request As acceso.guardar_usuarioRequest) As acceso.guardar_usuarioResponse Implements acceso.accesoServSoap.guardar_usuario
            Return MyBase.Channel.guardar_usuario(request)
        End Function
        
        Public Function guardar_usuario(ByVal nombre_corto As Object, ByVal Nombre_completo As Object, ByVal email_usuario As Object, ByVal nivel_usuario As Object, ByVal pasword As Object, ByVal id_scoi As Object, ByVal id_usuario As Object) As Object
            Dim inValue As acceso.guardar_usuarioRequest = New acceso.guardar_usuarioRequest()
            inValue.Body = New acceso.guardar_usuarioRequestBody()
            inValue.Body.nombre_corto = nombre_corto
            inValue.Body.Nombre_completo = Nombre_completo
            inValue.Body.email_usuario = email_usuario
            inValue.Body.nivel_usuario = nivel_usuario
            inValue.Body.pasword = pasword
            inValue.Body.id_scoi = id_scoi
            inValue.Body.id_usuario = id_usuario
            Dim retVal As acceso.guardar_usuarioResponse = CType(Me,acceso.accesoServSoap).guardar_usuario(inValue)
            Return retVal.Body.guardar_usuarioResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function acceso_accesoServSoap_guardar_usuarioAsync(ByVal request As acceso.guardar_usuarioRequest) As System.Threading.Tasks.Task(Of acceso.guardar_usuarioResponse) Implements acceso.accesoServSoap.guardar_usuarioAsync
            Return MyBase.Channel.guardar_usuarioAsync(request)
        End Function
        
        Public Function guardar_usuarioAsync(ByVal nombre_corto As Object, ByVal Nombre_completo As Object, ByVal email_usuario As Object, ByVal nivel_usuario As Object, ByVal pasword As Object, ByVal id_scoi As Object, ByVal id_usuario As Object) As System.Threading.Tasks.Task(Of acceso.guardar_usuarioResponse)
            Dim inValue As acceso.guardar_usuarioRequest = New acceso.guardar_usuarioRequest()
            inValue.Body = New acceso.guardar_usuarioRequestBody()
            inValue.Body.nombre_corto = nombre_corto
            inValue.Body.Nombre_completo = Nombre_completo
            inValue.Body.email_usuario = email_usuario
            inValue.Body.nivel_usuario = nivel_usuario
            inValue.Body.pasword = pasword
            inValue.Body.id_scoi = id_scoi
            inValue.Body.id_usuario = id_usuario
            Return CType(Me,acceso.accesoServSoap).guardar_usuarioAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function acceso_accesoServSoap_eliminar_usuario(ByVal request As acceso.eliminar_usuarioRequest) As acceso.eliminar_usuarioResponse Implements acceso.accesoServSoap.eliminar_usuario
            Return MyBase.Channel.eliminar_usuario(request)
        End Function
        
        Public Function eliminar_usuario(ByVal id_usuario As Object) As Object
            Dim inValue As acceso.eliminar_usuarioRequest = New acceso.eliminar_usuarioRequest()
            inValue.Body = New acceso.eliminar_usuarioRequestBody()
            inValue.Body.id_usuario = id_usuario
            Dim retVal As acceso.eliminar_usuarioResponse = CType(Me,acceso.accesoServSoap).eliminar_usuario(inValue)
            Return retVal.Body.eliminar_usuarioResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function acceso_accesoServSoap_eliminar_usuarioAsync(ByVal request As acceso.eliminar_usuarioRequest) As System.Threading.Tasks.Task(Of acceso.eliminar_usuarioResponse) Implements acceso.accesoServSoap.eliminar_usuarioAsync
            Return MyBase.Channel.eliminar_usuarioAsync(request)
        End Function
        
        Public Function eliminar_usuarioAsync(ByVal id_usuario As Object) As System.Threading.Tasks.Task(Of acceso.eliminar_usuarioResponse)
            Dim inValue As acceso.eliminar_usuarioRequest = New acceso.eliminar_usuarioRequest()
            inValue.Body = New acceso.eliminar_usuarioRequestBody()
            inValue.Body.id_usuario = id_usuario
            Return CType(Me,acceso.accesoServSoap).eliminar_usuarioAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function acceso_accesoServSoap_cambio_contrasenia(ByVal request As acceso.cambio_contraseniaRequest) As acceso.cambio_contraseniaResponse Implements acceso.accesoServSoap.cambio_contrasenia
            Return MyBase.Channel.cambio_contrasenia(request)
        End Function
        
        Public Function cambio_contrasenia(ByVal id As Object, ByVal pasword As Object) As Object
            Dim inValue As acceso.cambio_contraseniaRequest = New acceso.cambio_contraseniaRequest()
            inValue.Body = New acceso.cambio_contraseniaRequestBody()
            inValue.Body.id = id
            inValue.Body.pasword = pasword
            Dim retVal As acceso.cambio_contraseniaResponse = CType(Me,acceso.accesoServSoap).cambio_contrasenia(inValue)
            Return retVal.Body.cambio_contraseniaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function acceso_accesoServSoap_cambio_contraseniaAsync(ByVal request As acceso.cambio_contraseniaRequest) As System.Threading.Tasks.Task(Of acceso.cambio_contraseniaResponse) Implements acceso.accesoServSoap.cambio_contraseniaAsync
            Return MyBase.Channel.cambio_contraseniaAsync(request)
        End Function
        
        Public Function cambio_contraseniaAsync(ByVal id As Object, ByVal pasword As Object) As System.Threading.Tasks.Task(Of acceso.cambio_contraseniaResponse)
            Dim inValue As acceso.cambio_contraseniaRequest = New acceso.cambio_contraseniaRequest()
            inValue.Body = New acceso.cambio_contraseniaRequestBody()
            inValue.Body.id = id
            inValue.Body.pasword = pasword
            Return CType(Me,acceso.accesoServSoap).cambio_contraseniaAsync(inValue)
        End Function
    End Class
End Namespace
