'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace preorden_compra
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="preorden_compra.pre_orden_compraSoap")>  _
    Public Interface pre_orden_compraSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HelloWorld", ReplyAction:="*")>  _
        Function HelloWorld(ByVal request As preorden_compra.HelloWorldRequest) As preorden_compra.HelloWorldResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HelloWorld", ReplyAction:="*")>  _
        Function HelloWorldAsync(ByVal request As preorden_compra.HelloWorldRequest) As System.Threading.Tasks.Task(Of preorden_compra.HelloWorldResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Lista_productosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Lista_productos", ReplyAction:="*")>  _
        Function Lista_productos(ByVal request As preorden_compra.Lista_productosRequest) As preorden_compra.Lista_productosResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Lista_productos", ReplyAction:="*")>  _
        Function Lista_productosAsync(ByVal request As preorden_compra.Lista_productosRequest) As System.Threading.Tasks.Task(Of preorden_compra.Lista_productosResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HelloWorldRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HelloWorld", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As preorden_compra.HelloWorldRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As preorden_compra.HelloWorldRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class HelloWorldRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HelloWorldResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HelloWorldResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As preorden_compra.HelloWorldResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As preorden_compra.HelloWorldResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class HelloWorldResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public HelloWorldResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HelloWorldResult As String)
            MyBase.New
            Me.HelloWorldResult = HelloWorldResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Lista_productosRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Lista_productos", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As preorden_compra.Lista_productosRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As preorden_compra.Lista_productosRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class Lista_productosRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Lista_productosResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Lista_productosResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As preorden_compra.Lista_productosResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As preorden_compra.Lista_productosResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Lista_productosResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Lista_productosResult As Object
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Lista_productosResult As Object)
            MyBase.New
            Me.Lista_productosResult = Lista_productosResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface pre_orden_compraSoapChannel
        Inherits preorden_compra.pre_orden_compraSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class pre_orden_compraSoapClient
        Inherits System.ServiceModel.ClientBase(Of preorden_compra.pre_orden_compraSoap)
        Implements preorden_compra.pre_orden_compraSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function preorden_compra_pre_orden_compraSoap_HelloWorld(ByVal request As preorden_compra.HelloWorldRequest) As preorden_compra.HelloWorldResponse Implements preorden_compra.pre_orden_compraSoap.HelloWorld
            Return MyBase.Channel.HelloWorld(request)
        End Function
        
        Public Function HelloWorld() As String
            Dim inValue As preorden_compra.HelloWorldRequest = New preorden_compra.HelloWorldRequest()
            inValue.Body = New preorden_compra.HelloWorldRequestBody()
            Dim retVal As preorden_compra.HelloWorldResponse = CType(Me,preorden_compra.pre_orden_compraSoap).HelloWorld(inValue)
            Return retVal.Body.HelloWorldResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function preorden_compra_pre_orden_compraSoap_HelloWorldAsync(ByVal request As preorden_compra.HelloWorldRequest) As System.Threading.Tasks.Task(Of preorden_compra.HelloWorldResponse) Implements preorden_compra.pre_orden_compraSoap.HelloWorldAsync
            Return MyBase.Channel.HelloWorldAsync(request)
        End Function
        
        Public Function HelloWorldAsync() As System.Threading.Tasks.Task(Of preorden_compra.HelloWorldResponse)
            Dim inValue As preorden_compra.HelloWorldRequest = New preorden_compra.HelloWorldRequest()
            inValue.Body = New preorden_compra.HelloWorldRequestBody()
            Return CType(Me,preorden_compra.pre_orden_compraSoap).HelloWorldAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function preorden_compra_pre_orden_compraSoap_Lista_productos(ByVal request As preorden_compra.Lista_productosRequest) As preorden_compra.Lista_productosResponse Implements preorden_compra.pre_orden_compraSoap.Lista_productos
            Return MyBase.Channel.Lista_productos(request)
        End Function
        
        Public Function Lista_productos() As Object
            Dim inValue As preorden_compra.Lista_productosRequest = New preorden_compra.Lista_productosRequest()
            inValue.Body = New preorden_compra.Lista_productosRequestBody()
            Dim retVal As preorden_compra.Lista_productosResponse = CType(Me,preorden_compra.pre_orden_compraSoap).Lista_productos(inValue)
            Return retVal.Body.Lista_productosResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function preorden_compra_pre_orden_compraSoap_Lista_productosAsync(ByVal request As preorden_compra.Lista_productosRequest) As System.Threading.Tasks.Task(Of preorden_compra.Lista_productosResponse) Implements preorden_compra.pre_orden_compraSoap.Lista_productosAsync
            Return MyBase.Channel.Lista_productosAsync(request)
        End Function
        
        Public Function Lista_productosAsync() As System.Threading.Tasks.Task(Of preorden_compra.Lista_productosResponse)
            Dim inValue As preorden_compra.Lista_productosRequest = New preorden_compra.Lista_productosRequest()
            inValue.Body = New preorden_compra.Lista_productosRequestBody()
            Return CType(Me,preorden_compra.pre_orden_compraSoap).Lista_productosAsync(inValue)
        End Function
    End Class
End Namespace
