'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class perfil
    
    '''<summary>
    '''ASPxPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPanel1 As Global.DevExpress.Web.ASPxPanel
    
    '''<summary>
    '''ASPxImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxImage1 As Global.DevExpress.Web.ASPxImage
    
    '''<summary>
    '''ASPxCardView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxCardView1 As Global.DevExpress.Web.ASPxCardView
    
    '''<summary>
    '''SqlDataSourcePerfil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourcePerfil As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''ASPxRoundPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxRoundPanel1 As Global.DevExpress.Web.ASPxRoundPanel
    
    '''<summary>
    '''grid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grid As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''SqlDataSourceHKMiPerfil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceHKMiPerfil As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlDataSourceBitacoraHK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceBitacoraHK As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DetailNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DetailNotes As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''ASPxRoundPanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxRoundPanel2 As Global.DevExpress.Web.ASPxRoundPanel
    
    '''<summary>
    '''ASPxFormLayout1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1 As Global.DevExpress.Web.ASPxFormLayout
    
    '''<summary>
    '''ComboIDEntrada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComboIDEntrada As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''SqlDataSourceComboIndHK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceComboIndHK As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''TxtCodigoMatriz control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCodigoMatriz As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''TxtQue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtQue As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''TxtComo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtComo As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''TxtUnidadMedida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtUnidadMedida As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''ASPxFormLayout1_E1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1_E1 As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''ASPxFormLayout1_E2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1_E2 As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''TxtMedicion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtMedicion As Global.DevExpress.Web.ASPxMemo
    
    '''<summary>
    '''TxtOsemanal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtOsemanal As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''TxtOMensual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtOMensual As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''TxtOAnual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtOAnual As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''TxtPAnterior control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPAnterior As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''TxtMpaa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtMpaa As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''TxtPActual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPActual As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''TxtAMensual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtAMensual As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''TxtPAMensual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPAMensual As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''TxtDAMensual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDAMensual As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''TxtAAnual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtAAnual As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''TxtPAAnual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPAAnual As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''TxtDAAnual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDAAnual As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''TxtFactores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtFactores As Global.DevExpress.Web.ASPxMemo
    
    '''<summary>
    '''TxtAcciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtAcciones As Global.DevExpress.Web.ASPxMemo
    
    '''<summary>
    '''BtnGuardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnGuardar As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''ASPxGridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridView1 As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''TxtResponsable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtResponsable As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtPeriodicidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPeriodicidad As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtRojo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtRojo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtAzul control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtAzul As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtMinimo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtMinimo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtMaximo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtMaximo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtOperadorRojo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtOperadorRojo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtOperadorAzul control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtOperadorAzul As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtSemana control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSemana As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtMes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtMes As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtAno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtAno As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtPorc_AvancePActual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPorc_AvancePActual As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtPorc_AvancePAnterior control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPorc_AvancePAnterior As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtPorc_DAM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPorc_DAM As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtPorc_DAA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPorc_DAA As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtIDQuery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtIDQuery As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtStrConexion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtStrConexion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtStrConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtStrConsulta As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''SqlDataSourceEntradasHK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceEntradasHK As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''ASPxRoundPanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxRoundPanel3 As Global.DevExpress.Web.ASPxRoundPanel
    
    '''<summary>
    '''ASPxCardView2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxCardView2 As Global.DevExpress.Web.ASPxCardView
    
    '''<summary>
    '''SqlDataSourcePerfiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourcePerfiles As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''ASPxRoundPanel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxRoundPanel4 As Global.DevExpress.Web.ASPxRoundPanel
    
    '''<summary>
    '''ASPxGridView2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridView2 As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''SqlDataSourceActProcesos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceActProcesos As Global.System.Web.UI.WebControls.SqlDataSource
End Class
